import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { assertSameSeaAssets, observedFile, writeSeaBuildInputs } from "../scripts/sea-build-inputs.mjs";
import { outputName, resolveTarget } from "../scripts/sea-target.mjs";

const D = "a".repeat(64);

function fixture(root, overrides = {}) {
  const source = join(root, "entry.cjs");
  const executable = join(root, "agent.exe");
  writeFileSync(source, "input");
  writeFileSync(executable, "synthetic executable bytes");
  const observedInputs = [observedFile(source, "dist/input")];
  const input = { target: "x86_64-pc-windows-msvc", sourceMode: "host",
    hostBlobGeneratorNodeVersion: "v24.0.0", targetNodeVersion: "v24.0.0",
    downloadedChecksumProvenance: null, baseNodeBeforeSignatureRemoval: { logicalName: "base", bytes: 1, sha256: D },
    preInjectionBinary: { logicalName: "pre", bytes: 1, sha256: D },
    finalExecutable: observedFile(executable, "dist/gkos-agent.exe"), observedInputs, ...overrides };
  return { source, executable, input, recheck: () => ({ observedInputs: [observedFile(source, "dist/input")],
    finalExecutable: observedFile(executable, "dist/gkos-agent.exe") }) };
}

test("SEA inventory binds stable inputs and keeps SBOM scope incomplete", () => {
  const root = mkdtempSync(join(tmpdir(), "gkos-sea-inputs-"));
  try {
    const good = fixture(root);
    const output = join(root, "inventory.json");
    writeSeaBuildInputs(output, good.input, good.recheck);
    const parsed = JSON.parse(readFileSync(output));
    assert.equal(parsed.completeSbom, false);
    assert.equal(parsed.sourceMode, "host");
    const original = readFileSync(output);
    assert.throws(() => writeSeaBuildInputs(output, good.input, good.recheck), { code: "EEXIST" });
    assert.deepEqual(readFileSync(output), original);

    for (const change of [
      { observedInputs: [] },
      { observedInputs: [...good.input.observedInputs, good.input.observedInputs[0]] },
      { finalExecutable: { ...good.input.finalExecutable, sha256: "bad" } },
      { finalExecutable: { ...good.input.finalExecutable, sha256: "b".repeat(64) } },
      { downloadedChecksumProvenance: { tarball: "node.tar.gz", sha256: D, expectedSha256: D, shasumsUrl: "https://example.invalid", shasumsSha256: D } },
      { completeSbom: true },
    ]) assert.throws(() => writeSeaBuildInputs(join(root, Math.random().toString()), { ...good.input, ...change }, good.recheck));

    writeFileSync(good.source, "changed");
    assert.throws(() => writeSeaBuildInputs(join(root, "stale"), good.input, good.recheck), /changed/u);

    const downloaded = fixture(root, { sourceMode: "download", targetNodeVersion: "v22.20.0",
      downloadedChecksumProvenance: { tarball: "node-v22.20.0.tar.gz", sha256: D, expectedSha256: D,
        shasumsUrl: "https://nodejs.org/SHASUMS256.txt", shasumsSha256: D } });
    writeSeaBuildInputs(join(root, "downloaded.json"), downloaded.input, downloaded.recheck);

  } finally { /* Retain the isolated fixture for failure inspection. */ }
});

test("SEA inventory rejects physical output substitution before publishing", () => {
  const root = mkdtempSync(join(tmpdir(), "gkos-sea-output-")), f = fixture(root);
  const output = join(root, "inventory.json");
  writeFileSync(f.executable, "substituted executable bytes");
  assert.throws(() => writeSeaBuildInputs(output, f.input, f.recheck), /changed before inventory/u);
  assert.equal(existsSync(output), false);
});

test("SEA assets preserve keys and paths independently of insertion order", () => {
  const before = { "a.node": "/build/a.node", "b.node": "/build/b.node" };
  assert.doesNotThrow(() => assertSameSeaAssets(before, { "b.node": before["b.node"], "a.node": before["a.node"] }));
  for (const after of [{}, { ...before, "c.node": "/build/c.node" }, { ...before, "a.node": "/other/a.node" }]) {
    assert.throws(() => assertSameSeaAssets(before, after), /asset map changed/u);
  }
});

test("actual SEA command preserves generated bytes when inventory already exists", () => {
  const root = mkdtempSync(join(tmpdir(), "gkos-sea-preflight-"));
  mkdirSync(join(root, "scripts")); mkdirSync(join(root, "dist"));
  for (const name of ["build-sea.mjs", "sea-target.mjs", "sea-native-assets.mjs", "sea-build-inputs.mjs"]) {
    copyFileSync(new URL(`../scripts/${name}`, import.meta.url), join(root, "scripts", name));
  }
  const binary = outputName(resolveTarget(process.platform, process.arch));
  const names = ["gkos-desktop-agent.cjs", "sea-config.json", "sea-prep.blob", binary, `${binary}.build-inputs.json`];
  for (const name of names) writeFileSync(join(root, "dist", name), `preserved ${name}`);
  const before = names.map(name => readFileSync(join(root, "dist", name)));
  const run = spawnSync(process.execPath, [join(root, "scripts/build-sea.mjs")], { encoding: "utf8", timeout: 10_000 });
  assert.equal(run.error, undefined); assert.equal(run.status, 1);
  assert.match(run.stderr, /SEA build input inventory already exists/u);
  assert.deepEqual(readdirSync(join(root, "dist")).sort(), [...names].sort());
  names.forEach((name, index) => assert.deepEqual(readFileSync(join(root, "dist", name)), before[index]));
});
