import { timingSafeEqual } from "node:crypto";
import { base32LowerFirst130Bits, sha256Bytes } from "./canonical";
import { fault } from "./errors";
import type { AuthorityRandom } from "./types";
const CREDENTIAL = /^gkos1\.(gkc1_[a-z2-7]{26})\.([A-Za-z0-9_-]{43})$/u, DOMAIN = Buffer.from("GKOS-CREDENTIAL-V1\0", "utf8");
export interface GeneratedCredential { credential_id: string; secret_digest: string; wire: Buffer; destroy(): void; }
function secretDigest(secret: Uint8Array): Buffer { return sha256Bytes(Buffer.concat([DOMAIN, Buffer.from(secret)])); }
export function generateCredential(random: AuthorityRandom): GeneratedCredential { const secret = Buffer.from(random.bytes(32)); if (secret.length !== 32) throw new TypeError("random source length mismatch"); const digest = secretDigest(secret), credential_id = `gkc1_${base32LowerFirst130Bits(digest)}`, wire = Buffer.from(`gkos1.${credential_id}.${secret.toString("base64url")}`, "ascii"); secret.fill(0); if (wire.length !== 81) throw new Error("credential wire length mismatch"); return { credential_id, secret_digest: `sha256:${digest.toString("hex")}`, wire, destroy: () => wire.fill(0) }; }
export function parseCredential(wire: string | Uint8Array): { credential_id: string; digest: Buffer } { const bytes = typeof wire === "string" ? Buffer.from(wire, "utf8") : Buffer.from(wire); if (bytes.length !== 81 || !bytes.every((byte) => byte <= 0x7f)) fault("GKOS_P6_AUTH_FAILED"); const match = CREDENTIAL.exec(bytes.toString("ascii")); if (!match) fault("GKOS_P6_AUTH_FAILED"); const secret = Buffer.from(match[2], "base64url"); if (secret.length !== 32 || secret.toString("base64url") !== match[2]) { secret.fill(0); fault("GKOS_P6_AUTH_FAILED"); } const digest = secretDigest(secret), expected = `gkc1_${base32LowerFirst130Bits(digest)}`; secret.fill(0); if (!timingSafeEqual(Buffer.from(match[1], "ascii"), Buffer.from(expected, "ascii"))) fault("GKOS_P6_AUTH_FAILED"); return { credential_id: match[1], digest }; }
export function verifyCredentialDigest(presented: Buffer, stored: string, dummy: Buffer): boolean { const target = /^sha256:[0-9a-f]{64}$/u.test(stored) ? Buffer.from(stored.slice(7), "hex") : dummy; return target.length === 32 && timingSafeEqual(presented, target); }
