import { readFileSync } from "node:fs";
import { join } from "node:path";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import { canonicalBytes } from "./canonical";
import { fault } from "./errors";
import { PHASE6_CONTRACT_VERSION } from "./types";
export interface AcceptedOperation { operation: string; authority: "PUBLIC_AUTHENTICATED" | "LOCAL_BOOTSTRAP" | "OWNER_ONLY"; first_stage: "F2" | "F3"; idempotency: "required" | "not_applicable" | "derived_bootstrap_key"; mutates_authority: boolean; policy_capability: string; request_schema_ref: string; result_schema_ref: string; required_private_dependencies?: string[]; }
export class AcceptedContractValidator {
  readonly operations: ReadonlyMap<string, AcceptedOperation>; readonly requestValidators = new Map<string, ((value: unknown) => boolean) & { errors?: unknown }>(); readonly resultValidators = new Map<string, ((value: unknown) => boolean) & { errors?: unknown }>(); private readonly ajv: Ajv2020;
  constructor(readonly contractRoot: string) { const operationSchema = JSON.parse(readFileSync(join(contractRoot, "operation-inventory.schema.json"), "utf8")), toolSchema = JSON.parse(readFileSync(join(contractRoot, "tool-registry.schema.json"), "utf8")), inventory = JSON.parse(readFileSync(join(contractRoot, "operation-inventory.json"), "utf8")); this.ajv = new Ajv2020({ strict: true, strictSchema: true, strictTypes: true, strictTuples: true, allErrors: true, validateFormats: true, allowUnionTypes: true }); addFormats(this.ajv); this.ajv.addSchema(operationSchema, "operation-inventory.schema.json"); this.ajv.addSchema(toolSchema, "tool-registry.schema.json"); if (inventory.contract_version !== PHASE6_CONTRACT_VERSION || inventory.operation_count !== 32 || inventory.operations.length !== 32 || Object.keys(operationSchema.$defs).length !== 54) throw new Error("accepted operation inventory coordinate mismatch"); const counts: Record<string, number> = { PUBLIC_AUTHENTICATED: 0, LOCAL_BOOTSTRAP: 0, OWNER_ONLY: 0 }, operations = new Map<string, AcceptedOperation>(); for (const operation of inventory.operations as AcceptedOperation[]) { if (operations.has(operation.operation) || !(operation.authority in counts)) throw new Error("accepted operation inventory invalid"); counts[operation.authority]++; operations.set(operation.operation, Object.freeze({ ...operation })); const request = this.ajv.getSchema(operation.request_schema_ref), result = this.ajv.getSchema(operation.result_schema_ref); if (!request || !result) throw new Error(`unresolved accepted operation schema: ${operation.operation}`); this.requestValidators.set(operation.operation, request as never); this.resultValidators.set(operation.operation, result as never); } if (counts.PUBLIC_AUTHENTICATED !== 7 || counts.LOCAL_BOOTSTRAP !== 1 || counts.OWNER_ONLY !== 24) throw new Error("accepted authority counts mismatch"); this.operations = operations; }
  operation(name: string): AcceptedOperation { const operation = this.operations.get(name); if (!operation) fault("GKOS_P6_UNKNOWN_OPERATION"); return operation; }
  validateRequest(name: string, value: unknown): void { if (canonicalBytes(value).length > 262144) fault("GKOS_P6_PAYLOAD_TOO_LARGE"); const validate = this.requestValidators.get(name); if (!validate || !validate(value)) fault("GKOS_P6_INVALID_PARAMS"); }
  validateResult(name: string, value: unknown): void { if (canonicalBytes(value).length > 1048576) fault("GKOS_P6_INTERNAL_ERROR"); const validate = this.resultValidators.get(name); if (!validate || !validate(value)) fault("GKOS_P6_INTERNAL_ERROR"); }
}
