import { DatabaseSync } from "node:sqlite";
import { chmodSync, existsSync } from "node:fs";
import { join } from "node:path";
import { requireQualifiedPosixRoot } from "./filesystem";
import { fault } from "./errors";

export const AUTHORITY_TABLES = Object.freeze([
  "authority_meta", "agent_identities", "credentials", "external_mappings", "sessions", "requests", "activities", "policy_decisions", "identity_audit_receipts", "retention_batches", "rate_buckets", "bootstrap_migrations", "page_snapshots", "page_cursors", "effect_outbox_events", "restore_events",
]);
const PREFIX = "contract_version TEXT NOT NULL, vault_id TEXT NOT NULL, authority_instance_id TEXT NOT NULL, restore_epoch INTEGER NOT NULL CHECK(restore_epoch>=1)";
const EVENT = `${PREFIX}, event_id TEXT PRIMARY KEY, event_kind TEXT NOT NULL, global_event_seq INTEGER NOT NULL UNIQUE CHECK(global_event_seq>=1), authority_instance_id_before TEXT NOT NULL, authority_instance_id_after TEXT NOT NULL, restore_epoch_before INTEGER NOT NULL, restore_epoch_after INTEGER NOT NULL, authority_generation_before INTEGER NOT NULL, authority_generation_after INTEGER NOT NULL, agent_id TEXT, auth_epoch_before INTEGER, auth_epoch_after INTEGER, transport TEXT NOT NULL, occurred_at TEXT NOT NULL, predecessor_event_digest TEXT NOT NULL, event_digest TEXT NOT NULL UNIQUE`;
const DDL = `
CREATE TABLE IF NOT EXISTS authority_meta (${PREFIX}, meta_id TEXT PRIMARY KEY CHECK(meta_id='authority'), schema_version TEXT NOT NULL, authority_generation INTEGER NOT NULL CHECK(authority_generation>=1), global_event_seq INTEGER NOT NULL CHECK(global_event_seq>=1), global_event_head_digest TEXT NOT NULL, event_history_floor_seq INTEGER NOT NULL CHECK(event_history_floor_seq>=1), event_history_floor_predecessor_digest TEXT NOT NULL, write_gate TEXT NOT NULL CHECK(write_gate IN ('open','recovery_required','blocked')), bootstrap_state TEXT NOT NULL, retention_days INTEGER NOT NULL CHECK(retention_days BETWEEN 7 AND 365), retention_effective_from TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS agent_identities (${PREFIX}, agent_id TEXT PRIMARY KEY, authority_role TEXT NOT NULL CHECK(authority_role IN ('owner','agent')), display_name TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','disabled')), authority_generation INTEGER NOT NULL, auth_epoch INTEGER NOT NULL CHECK(auth_epoch>=1), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, disabled_at TEXT, disable_reason TEXT, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS credentials (${PREFIX}, credential_id TEXT PRIMARY KEY, agent_id TEXT NOT NULL REFERENCES agent_identities(agent_id), credential_role TEXT NOT NULL CHECK(credential_role IN ('owner_admin','agent')), format TEXT NOT NULL CHECK(format IN ('gkos1','legacy-hex-v0')), digest_algorithm TEXT NOT NULL CHECK(digest_algorithm IN ('sha256-domain-separated','legacy-sha256-domain-separated')), secret_digest TEXT NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN ('active','revoked')), credential_generation INTEGER NOT NULL, authority_generation_issued INTEGER NOT NULL, auth_epoch_issued INTEGER NOT NULL, authority_generation_revoked INTEGER, auth_epoch_revoked INTEGER, revoked_at TEXT, revocation_reason TEXT, replaces_credential_id TEXT, created_at TEXT NOT NULL, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS external_mappings (${PREFIX}, mapping_id TEXT PRIMARY KEY, namespace TEXT NOT NULL, subject_digest TEXT NOT NULL, agent_id TEXT NOT NULL REFERENCES agent_identities(agent_id), authority_generation INTEGER NOT NULL, auth_epoch INTEGER NOT NULL, mapping_generation INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','revoked')), authenticated_by TEXT NOT NULL, created_at TEXT NOT NULL, revoked_at TEXT, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (${PREFIX}, session_id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, auth_epoch INTEGER NOT NULL, credential_id TEXT NOT NULL, transport TEXT NOT NULL, authority_generation_at_open INTEGER NOT NULL, status TEXT NOT NULL CHECK(status IN ('open','closed','expired','stale')), created_at TEXT NOT NULL, last_activity_at TEXT NOT NULL, idle_expires_at TEXT NOT NULL, absolute_expires_at TEXT NOT NULL, closed_at TEXT, close_reason TEXT, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS requests (${PREFIX}, request_id TEXT PRIMARY KEY, session_id TEXT, agent_id TEXT NOT NULL, credential_id TEXT NOT NULL, transport TEXT NOT NULL, operation TEXT NOT NULL, authority_generation_admitted INTEGER NOT NULL, auth_epoch_admitted INTEGER NOT NULL, authority_generation_final INTEGER, auth_epoch_final INTEGER, idempotency_key_digest TEXT, input_digest TEXT NOT NULL, input_bytes INTEGER NOT NULL, state TEXT NOT NULL CHECK(state IN ('admitted','executing','committed','rejected','failed','cancelled')), admitted_at TEXT NOT NULL, deadline_at TEXT NOT NULL, completed_at TEXT, result_digest TEXT, error_code TEXT, record_digest TEXT NOT NULL, UNIQUE(agent_id,operation,idempotency_key_digest));
CREATE TABLE IF NOT EXISTS activities (${PREFIX}, activity_id TEXT PRIMARY KEY, activity_seq INTEGER NOT NULL UNIQUE, agent_id TEXT NOT NULL, auth_epoch INTEGER NOT NULL, credential_id TEXT NOT NULL, session_id TEXT, request_id TEXT NOT NULL, transport TEXT NOT NULL, authority_generation INTEGER NOT NULL, operation TEXT NOT NULL, outcome TEXT NOT NULL CHECK(outcome IN ('allowed','denied','failed','cancelled')), policy_decision_id TEXT NOT NULL, input_digest TEXT NOT NULL, result_digest TEXT, error_code TEXT, started_at TEXT NOT NULL, finished_at TEXT NOT NULL, duration_ms INTEGER NOT NULL CHECK(duration_ms>=0), metadata TEXT NOT NULL, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS policy_decisions (${PREFIX}, policy_decision_id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, auth_epoch INTEGER NOT NULL, session_id TEXT, request_id TEXT NOT NULL, transport TEXT NOT NULL, authority_generation INTEGER NOT NULL, capability TEXT NOT NULL, policy_digest TEXT NOT NULL, configuration_digest TEXT NOT NULL, outcome TEXT NOT NULL CHECK(outcome IN ('allow','deny','indeterminate')), reason_codes TEXT NOT NULL, evaluated_at TEXT NOT NULL, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS identity_audit_receipts (${EVENT}, request_id TEXT, idempotency_key_digest TEXT, before_digest TEXT, after_digest TEXT, actor TEXT NOT NULL CHECK(actor IN ('local_owner','system_bootstrap','system_migration')), action TEXT NOT NULL CHECK(action IN ('bootstrap_owner','bootstrap_legacy_agent','provision_agent','rename_agent','disable_agent','enable_agent','issue_credential','revoke_credential','rotate_credential','add_mapping','revoke_mapping','close_session','set_retention','migration_recovery')), target_type TEXT NOT NULL CHECK(target_type IN ('authority','agent','credential','mapping','session','retention','migration')), target_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS retention_batches (${EVENT}, record_type TEXT NOT NULL, first_sequence INTEGER NOT NULL, last_sequence INTEGER NOT NULL, row_count INTEGER NOT NULL CHECK(row_count BETWEEN 1 AND 1000), ordered_rows_digest TEXT NOT NULL, retention_policy_digest TEXT NOT NULL, deleted_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rate_buckets (${PREFIX}, bucket_id TEXT PRIMARY KEY, agent_id TEXT, auth_epoch INTEGER, authority_generation INTEGER NOT NULL, bucket_class TEXT NOT NULL, tokens_micro INTEGER NOT NULL, capacity_micro INTEGER NOT NULL, refill_micro_per_ms INTEGER NOT NULL, last_refill_wall_at TEXT NOT NULL, last_refill_monotonic_ms INTEGER NOT NULL, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bootstrap_migrations (${PREFIX}, migration_id TEXT PRIMARY KEY, authority_generation INTEGER NOT NULL, agent_id TEXT, auth_epoch INTEGER, legacy_credential_id TEXT, legacy_source TEXT NOT NULL CHECK(legacy_source IN ('absent','desktop_agent_token')), state TEXT NOT NULL CHECK(state IN ('UNINITIALIZED','OWNER_PROVED','PLAN_STAGED','OWNER_LOCATOR_STAGED','DB_PUBLISHED','OWNER_ACTIVE','LEGACY_REMOVED','COMPLETE','RECOVERY_REQUIRED')), plan_digest TEXT NOT NULL, source_digest TEXT NOT NULL, database_digest TEXT NOT NULL, anchor_proposal_digest TEXT NOT NULL, genesis_event_id TEXT NOT NULL, idempotency_key_digest TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS page_snapshots (${PREFIX}, snapshot_id TEXT PRIMARY KEY, agent_id TEXT NOT NULL, auth_epoch INTEGER NOT NULL, session_id TEXT, transport TEXT NOT NULL, authority_generation INTEGER NOT NULL, operation TEXT NOT NULL, filter_digest TEXT NOT NULL, order_version TEXT NOT NULL, entry_count INTEGER NOT NULL CHECK(entry_count BETWEEN 0 AND 2000), canonical_bytes INTEGER NOT NULL CHECK(canonical_bytes BETWEEN 0 AND 524288), snapshot_digest TEXT NOT NULL, issued_reference_count INTEGER NOT NULL CHECK(issued_reference_count BETWEEN 0 AND 2000), issued_reference_set_digest TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS page_cursors (${PREFIX}, cursor_digest TEXT PRIMARY KEY, snapshot_id TEXT NOT NULL REFERENCES page_snapshots(snapshot_id), agent_id TEXT NOT NULL, auth_epoch INTEGER NOT NULL, session_id TEXT, transport TEXT NOT NULL, authority_generation INTEGER NOT NULL, operation TEXT NOT NULL, filter_digest TEXT NOT NULL, page_offset INTEGER NOT NULL, page_limit INTEGER NOT NULL CHECK(page_limit BETWEEN 1 AND 100), order_version TEXT NOT NULL, issued_at TEXT NOT NULL, expires_at TEXT NOT NULL, record_digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS effect_outbox_events (${EVENT}, credential_id TEXT NOT NULL, session_id TEXT, request_id TEXT NOT NULL, policy_decision_id TEXT NOT NULL, input_digest TEXT NOT NULL, plan_digest TEXT NOT NULL, effect_id TEXT NOT NULL, attempt INTEGER NOT NULL, bridge_state TEXT NOT NULL CHECK(bridge_state IN ('PREPARED','EFFECT_TERMINAL_OBSERVED','AUDIT_PUBLISHED','RECOVERED')), expected_recovery_gate_digest TEXT NOT NULL, effects_receipt_digest TEXT, effects_journal_digest TEXT, effects_archive_digest TEXT, activity_id TEXT, UNIQUE(vault_id,authority_instance_id,effect_id,attempt,bridge_state));
CREATE TABLE IF NOT EXISTS restore_events (${EVENT}, actor TEXT NOT NULL CHECK(actor='local_owner_recovery'), action TEXT NOT NULL CHECK(action IN ('authority_restore','authority_restore_abort')), target_type TEXT NOT NULL CHECK(target_type IN ('authority_instance','restore_plan')), target_id TEXT NOT NULL, request_id TEXT NOT NULL, restore_plan_digest TEXT NOT NULL, backup_id TEXT NOT NULL, backup_digest TEXT NOT NULL, old_authority_instance_id TEXT NOT NULL, new_authority_instance_id TEXT, old_restore_epoch INTEGER NOT NULL, new_restore_epoch INTEGER, old_authority_generation INTEGER NOT NULL, new_authority_generation INTEGER, replacement_owner_agent_id TEXT, replacement_credential_id TEXT, candidate_credential_digest TEXT NOT NULL, locator_binding_digest TEXT, revoked_credentials_digest TEXT, closed_sessions_digest TEXT, invalidated_refs_digest TEXT, restored_database_digest TEXT, expected_temp_identity_digest TEXT, expected_temp_protection_digest TEXT, temporary_disposition TEXT, replacement_active INTEGER NOT NULL, database_published INTEGER NOT NULL, anchor_published INTEGER NOT NULL, abort_intent_digest TEXT, tombstone_digest TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_owner ON agent_identities(authority_role) WHERE authority_role='owner' AND status='active';
CREATE UNIQUE INDEX IF NOT EXISTS one_active_external_subject ON external_mappings(namespace,subject_digest) WHERE status='active';
CREATE INDEX IF NOT EXISTS active_credential_by_agent ON credentials(agent_id,status);
CREATE INDEX IF NOT EXISTS request_idempotency ON requests(agent_id,operation,idempotency_key_digest);
`;

export class AuthorityDatabase {
  readonly path: string; readonly db: any;
  constructor(root: string) {
    this.path = join(requireQualifiedPosixRoot(root), "authority.sqlite3"); const existed = existsSync(this.path);
    try { this.db = new DatabaseSync(this.path); this.db.exec("PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA trusted_schema=OFF; PRAGMA busy_timeout=5000; PRAGMA page_size=4096; PRAGMA max_page_count=131072;"); if (!existed) chmodSync(this.path, 0o600); this.db.exec(`BEGIN IMMEDIATE; ${DDL} COMMIT;`); this.assertInventory(); }
    catch { try { this.db?.close(); } catch {} fault("GKOS_P6_AUTHORITY_CORRUPT"); }
  }
  transaction<T>(work: () => T): T { this.db.exec("BEGIN IMMEDIATE"); try { const result = work(); this.db.exec("COMMIT"); return result; } catch (error) { try { this.db.exec("ROLLBACK"); } catch {} throw error; } }
  insert(table: string, record: Record<string, unknown>): void { if (!(AUTHORITY_TABLES as readonly string[]).includes(table)) throw new Error("unknown authority table"); const fields=Object.keys(record); const sql=`INSERT INTO ${table} (${fields.join(",")}) VALUES (${fields.map(()=>"?").join(",")})`; this.db.prepare(sql).run(...fields.map((field)=>record[field] === undefined ? null : record[field])); }
  assertInventory(): void { const rows = this.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all() as {name:string}[]; const names = rows.map((row) => row.name); const expected = [...AUTHORITY_TABLES].sort(); if (JSON.stringify(names) !== JSON.stringify(expected)) fault("GKOS_P6_AUTHORITY_CORRUPT"); }
  close(): void { this.db.close(); }
}
